(defstruct movie
title director year type
  )
(defun add-movie (movie array)
  (let ((length (length array))
        (found NIL)
        (spot NIL)
        )
    (dotimes (i length)
      (let ((current (aref array i)))
        (when (and (not spot) (null (aref array i)))
          (setf spot i)
          )
        (when (string= (movie-title current) (movie-title movie))
          (setq found t)
          )        
        )
      )
    (if (or found (not spot))
        NIL
        (setf (aref array spot) movie)
        )  
    )

  )
